### ISSUE TITLE
Repository name doesn't follow conventions of capitalization in the word "MiSTer"

### ISSUE THREAD

**Issue by dshadoff** [MiSTer-devel/Arcade-AsteroidsDeluxe_Mister#5]
Repository name doesn't follow conventions of capitalization in the word "MiSTer", however Arcade-Asteroids_MiSTer does.

There is a separate issue with the updater script which searches for these cores using a separately-miscapitalized "_MISTer" suffix (with an incorrect capital "I"), which is logged with the script maintainer.

**Comment by alanswx** [comment]
fixed
